version: "3.3"
services:
    mongodb:
        image: mongo
        restart: always
        volumes:
            - db-data:/data/db

    server:
        image: ghcr.io/davidilie/sharex-upload-server/server
        restart: always
        depends_on:
            - mongodb
        ports:
            - 4000:4000
        volumes:
            - uploads:/usr/src/app/server/uploads
        environment:
            - PORT=4000
            - MONGO_URI=mongodb
            - FRONTEND_URL=http://localhost
            - ENV=PRODUCTION
            - API_URL=http://localhost
            - ACCESS_TOKEN_SECRET=ioasbdiuabsdiuasduibasdo
        links:
            - mongodb

    web:
        image: ghcr.io/davidilie/sharex-upload-server/web
        restart: always
        depends_on:
            - mongodb
            - server
        ports:
            - 3000:3000
        environment:
            - APP_URL=http://localhost
            - API_URL=http://localhost
            - SERVER_API_URL=http://server:4000
        links:
            - server

    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - server
            - web

volumes:
    sharex-upload-server-db:
        driver: local
    sharex-upload-server-data:
        driver: local
