name: "build_deploy_app"

on:
    push:
        branches:
            - master

jobs:
    server:
        name: "Build Server"
        runs-on: ubuntu-latest
        steps:
            - name: "Build:checkout"
              uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: DavidIlie
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Build and publish Docker image
              run: |
                  docker build -t ghcr.io/davidilie/sharex-media-server:server -f server/Dockerfile .
                  docker push ghcr.io/davidilie/sharex-media-server:server
    web:
        name: "Build Web"
        runs-on: ubuntu-latest
        steps:
            - name: "Build:checkout"
              uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: DavidIlie
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Build and publish Docker image
              run: |
                  docker build -t ghcr.io/davidilie/sharex-media-server:web -f web/Dockerfile .
                  docker push ghcr.io/davidilie/sharex-media-server:web
    deploy_self:
        name: "Deploy"
        runs-on: ubuntu-latest
        needs: [server, web]
        steps:
            - uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: |
                      rollout restart deploy web -n sharex-media-server
                      kubectl rollout restart deploy server -n sharex-media-server
