name: "build_deploy_app"

on:
    push:
        branches:
            - master
        paths:
            - "common/**"
            - "server/**"
            - "web/**"

jobs:
    server:
        name: "Build Server"
        runs-on: ubuntu-latest
        steps:
            - name: "Build:checkout"
              uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: DavidIlie
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Build and publish Docker image
              run: |
                  docker build -t ghcr.io/davidilie/sharex-media-server:server -f server/Dockerfile .
                  docker push ghcr.io/davidilie/sharex-media-server:server
    web:
        name: "Build Web"
        runs-on: ubuntu-latest
        steps:
            - name: "Build:checkout"
              uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: DavidIlie
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Build and publish Docker image
              run: |
                  docker build -t ghcr.io/davidilie/sharex-media-server:web -f web/Dockerfile .
                  docker push ghcr.io/davidilie/sharex-media-server:web
    deploy_self:
        name: "Deploy"
        runs-on: ubuntu-latest
        needs: [server, web]
        steps:
            - name: "Set Kubernetes Context"
              uses: Azure/k8s-set-context@v1
              with:
                  method: kubeconfig
                  kubeconfig: ${{ secrets.KUBE_CONFIG }}
            - name: "Restart web deployment"
              run: kubectl rollout restart deploy web -n sharex-media-server
            - name: "Restart server deployment"
              run: kubectl rollout restart deploy server -n sharex-media-server
